# Generated by Django 2.2.17 on 2020-11-06 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0002_user_model_extend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 15, 48, 21, 367457, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
