# Generated by Django 2.2.17 on 2020-11-07 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0003_user_model_extend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 14, 54, 1, 138000, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
