# Generated by Django 2.2.17 on 2020-11-10 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0004_auto_20201107_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 12, 31, 28, 650630, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
