# Generated by Django 2.2.17 on 2020-11-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_user_profile'),
    ]

    operations = [
    ]
